MIN_WIZARDS, MAX_WIZARDS, MAX_SPELLS = 2, 8, 18
WIZARD_NAME_SET = ['Astoroth','Bellatrix','Corwin','Desiderius','Erza','Fizban','Gandalf','Hermione']
from zx_gfx import PALETTE, BLACK, BLUE, RED, MAGENTA, GREEN, CYAN, YELLOW, WHITE, BRIGHT_BLUE, BRIGHT_RED, BRIGHT_MAGENTA, BRIGHT_GREEN, BRIGHT_CYAN, BRIGHT_YELLOW, BRIGHT_WHITE
F_MOUNT, F_MOUNT_ANY, F_FLYING, F_UNDEAD, F_TREE, F_EXPIRES, F_EXPIRES_SPELL, F_NOCORPSE, F_INVULN, F_STRUCT, F_ETH, F_ENGULFS, F_SPREADS = 'mount', 'mountAny', 'flying', 'undead', 'tree', 'expires', 'expiresGivesSpell', 'noCorpse', 'invuln', 'struct', 'trans', 'engulf', 'spread'
FLAGS = [F_MOUNT, F_MOUNT_ANY, F_FLYING, F_UNDEAD, F_TREE, F_EXPIRES, F_EXPIRES_SPELL, F_NOCORPSE, F_INVULN, F_STRUCT, F_ETH, F_ENGULFS, F_SPREADS] 

creations = []
newCreations = []

corpses = [] # list of corpse objects in the form [{'creation': creation}] 
victims = [] # list of objects trapped by blobs in the form [{'creation': creation}]

# wizard 0 is unused
wizards = [
    {
        'name': f'{WIZARD_NAME_SET[i-1]}',  # name string with iteration counter
        'owner': i,
        'sprite': 1 + (hash(3*i) % 7), # randomising without using rand; value is 1..7 inclusive
        'palette': 1 + (hash(4*i) % 7),
        # 'frame_set': [('modwizard0', RED), ('modwizard1', GREEN), ('modwizard2', BLUE)],
        'frame_set': None,
        'level': 0,
        'combat': 1,
        'rangedCombat': 0,
        'rangedCombatRange': 0,
        'defence': 2,
        'movement': 1,
        'manvr': 8,
        'magicRes': 8,
        'ability': 0,
        'spell_book': [],
        'selected': None, # Next spell
        'illusion': False, # Whether next spell is going to be an illusory creature
        'multicast': 0, # Some spells have multiple casts
        'has_moved': False,
        'engaged': False,
        'mounted': False,
        'flying': False,
        'shadow': False,
        'armed': False,
        'defeated': True,
        'x': 0,
        'y': 0
    } for i in range(MAX_WIZARDS + 1)]  # Up to 8 wizards with iteration counter
wizards[1]['level'], wizards[1]['sprite'], wizards[1]['palette'] = 0, 1, 14

spell_list = [
    {'spell_name': 'disbelieve', 'label': 'disbelieve', 'msg': 'If your opponent was foolish enough to rely upon an illusion, this will dispel it!', 'chance': 9, 'distance': 127, 'law': 0, 'multicast': 1, 'priority': 0},
    {'spell_name': 'meditate', 'label': 'meditate', 'msg': 'I dare you to sit still, close your eyes and summon up another spell for your whole turn.', 'chance': 1, 'distance': 0, 'law': 0, 'multicast': 1, 'priority': 0},
    {'spell_name': 'creature_cast_spell (king_cobra)', 'label': 'king_cobra', 'msg': 'The noble King Cobra\'s agility allows it to weave through battles, dodging attacks and striking quickly.', 'chance': 8, 'distance': 1, 'law': 1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (dire_wolf)', 'label': 'dire_wolf', 'msg': 'The fierce Dire Wolf is fast, agile and highly resistant to magic.', 'chance': 8, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (goblin)', 'label': 'goblin', 'msg': 'The only thing that goblins really have going for them is that they\'re fairly hard to hit.', 'chance': 8, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (crocodile)', 'label': 'crocodile', 'msg': 'Surprisingly agile and unsurprisingly tough, they are however quite vulnerable to magic.', 'chance': 7, 'distance': 1, 'law': 0, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (faun)', 'label': 'faun', 'msg': 'The faun is clumsy and slow but it\'s known for its magic resistance.', 'chance': 7, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (lion)', 'label': 'lion', 'msg': 'The awesome lion is fast, agile, deadly and highly resistant to magic.', 'chance': 5, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (elf)', 'label': 'elf', 'msg': 'Vulnerable to melee and close encounters in general, the elegant elf relies on her lethal longbow', 'chance': 6, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    # {'spell_name': 'creature_cast_spell (orc)', 'label': 'orc', 'msg': 'Much better occupied here that off drinking, looting and comitting war-crimes in neighbouring democracies', 'chance': 9, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (orc)', 'label': 'orc', 'msg': 'Not so scary when they\'re on their own.', 'chance': 9, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (bear)', 'label': 'bear', 'msg': 'A fearsome all-rounder with real staying power.', 'chance': 5, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (gorilla)', 'label': 'gorilla', 'msg': 'Gorillas are agile, tough, and smarter than they look.', 'chance': 6, 'distance': 1, 'law': 0, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (ogre)', 'label': 'ogre', 'msg': 'Ogres are big, clumsy and intimidating but quite vulnerable to magic.', 'chance': 6, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (hydra)', 'label': 'hydra', 'msg': 'The legendery hydra is a terrifying foe. Magic may be your best bet.', 'chance': 4, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (giant_rat)', 'label': 'giant_rat', 'msg': 'Ah, so they do exist. Highly agile and extremely resistant to magic.', 'chance': 9, 'distance': 1, 'law': 0, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (giant)', 'label': 'giant', 'msg': 'With a melee attack nobody gets up from, the giant is precisely what you\'d expect.', 'chance': 3, 'distance': 1, 'law': 1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (horse)', 'label': 'horse', 'msg': 'A wizard\'s best friend. Horses are fast, incredibly agile and supremely resistant to magic', 'chance': 8, 'distance': 1, 'law': 1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (unicorn)', 'label': 'unicorn', 'msg': 'Way less agile than a horse but much, much more deadly and, unbelievably, even more magic resistant.', 'chance': 5, 'distance': 1, 'law': 2, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (centaur)', 'label': 'centaur', 'msg': 'Half human and 7/8ths horse, this creature is wielding a huge bow.', 'chance': 6, 'distance': 1, 'law': 1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (pegasus)', 'label': 'pegasus', 'msg': 'While large and clumsy on the ground, the pegasus has rescued many a wizard.', 'chance': 5, 'distance': 1, 'law': 2, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (gryphon)', 'label': 'gryphon', 'msg': 'Tough air-borne all-rounders like the gryphon can make for great mounts.', 'chance': 5, 'distance': 1, 'law': 1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (manticore)', 'label': 'manticore', 'msg': 'A flying tank with ranged attacks makes for a formidable mount.', 'chance': 3, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (bat)', 'label': 'bat', 'msg': 'Well, they\'re quick, adorable and incredibly resistant to magic. Every wizard should have one.', 'chance': 7, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (green_dragon)', 'label': 'green_dragon', 'msg': 'The smallest of the dragons, it\'s still a dragon! And its breath travels a long way!', 'chance': 0, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (red_dragon)', 'label': 'red_dragon', 'msg': 'The terrifying red dragon\'s breath is to be feared for sure but up close you\'re in real trouble.', 'chance': 0, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (golden_dragon)', 'label': 'golden_dragon', 'msg': 'The mighty golden dragon can change fates in an instant.', 'chance': 0, 'distance': 1, 'law': 2, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (harpy)', 'label': 'harpy', 'msg': 'So annoying to wizards and sooth-sayers, (the surviving) harpies have high magic resistance.', 'chance': 5, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (eagle)', 'label': 'eagle', 'msg': 'An historic ally of wizards everywhere, giant eagles are fast and seemingly built for wizard wars.', 'chance': 6, 'distance': 1, 'law': 1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (vampire)', 'label': 'vampire', 'msg': 'Hard to hit, hard to even see - this undead creature is a quick, dangerous killer.', 'chance': 1, 'distance': 1, 'law': -2, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (ghost)', 'label': 'ghost', 'msg': 'These restless spirits have high magic resistance, graceful flight and an aversion to proton packs.', 'chance': 4, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (spectre)', 'label': 'spectre', 'msg': 'The shimmering form of the frail spectre is wielding a mighty longsword.', 'chance': 5, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (wraith)', 'label': 'wraith', 'msg': 'This undead creature is more powerful than most and faster, too.', 'chance': 4, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (skeleton)', 'label': 'skeleton', 'msg': 'Almost every wizard falls back on skeletons at some point. It\'s the abundant supply.', 'chance': 6, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (zombie)', 'label': 'zombie', 'msg': 'Slow, weak and only really dangerous in numbers, they are nonetheless undead! Equip accordingly.', 'chance': 8, 'distance': 1, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (Goey Blob)', 'label': 'Goey Blob', 'msg': 'Left unchecked these apparently harmless globs will spread rapidly and envelope unsuspecting creatures.', 'chance': 8, 'distance': 6, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'creature_cast_spell (Magic Fire)', 'label': 'Magic Fire', 'msg': 'This stuff spreads like wildfire and it can only be stopped by hunting down its creator.', 'chance': 7, 'distance': 6, 'law': -1, 'multicast': 1, 'priority': 18},
    {'spell_name': 'trees_castles_spell (Magic Wood)', 'label': 'Magic Wood', 'msg': 'Any wizard can seek safety climbing these trees. Sometimes spells fall out.', 'chance': 7, 'distance': 8, 'law': 1, 'multicast': 8, 'priority': 17},
    {'spell_name': 'trees_castles_spell (Shadow Wood)', 'label': 'Shadow Wood', 'msg': 'Trees don\'t move. Much. Don\'t get too close in case we\'re wrong.', 'chance': 3, 'distance': 8, 'law': -1, 'multicast': 8, 'priority': 18},
    {'spell_name': 'trees_castles_spell (Magic Castle)', 'label': 'Magic Castle', 'msg': 'An indestructible safe haven... until it suddenly isn\'t.', 'chance': 4, 'distance': 8, 'law': 1, 'multicast': 1, 'priority': 23},
    {'spell_name': 'trees_castles_spell (Dark Citadel)', 'label': 'Dark Citadel', 'msg': 'An indestructible safe haven... until it suddenly isn\'t.', 'chance': 4, 'distance': 8, 'law': -1, 'multicast': 1, 'priority': 23},
    {'spell_name': 'wall_spell', 'label': 'wall', 'msg': 'Walls. Nobody likes people who build walls. Walls are a terrible idea.', 'chance': 7, 'distance': 6, 'law': 0, 'multicast': 4, 'priority': 12},
    {'spell_name': 'lightning_spell (Magic Bolt)', 'label': 'Magic Bolt', 'msg': 'The wizard channels their abilties into launching a direct energy bolt.', 'chance': 9, 'distance': 6, 'law': 0, 'multicast': 1, 'priority': 18},
    {'spell_name': 'lightning_spell (Lightning)', 'label': 'Lightning', 'msg': 'Lightning bolt! The wizard\'s abilities are amplified into a crackling lightning bolt.', 'chance': 9, 'distance': 4, 'law': 0, 'multicast': 1, 'priority': 18},
    {'spell_name': 'dark_power_spell (Vengeance)', 'label': 'Vengeance', 'msg': 'A long-distance indirect magical attack on a creature or wizard\'s mind.', 'chance': 7, 'distance': 15, 'law': -1, 'multicast': 1, 'priority': 12},
    {'spell_name': 'dark_power_spell (Decree)', 'label': 'Decree', 'msg': 'A long-distance indirect magical attack on a creature or wizard\'s mind.', 'chance': 7, 'distance': 15, 'law': 1, 'multicast': 1, 'priority': 12},
    {'spell_name': 'dark_power_spell (Dark Power)', 'label': 'Dark Power', 'msg': 'A powerful sequence of indirect magical mental attacks can destroy creatures or ruin a victim wizard\'s day.', 'chance': 4, 'distance': 15, 'law': -2, 'multicast': 3, 'priority': 11},
    {'spell_name': 'dark_power_spell (Justice)', 'label': 'Justice', 'msg': 'A powerful sequence of indirect magical mental attacks can destroy creatures or ruin a victim wizard\'s day.', 'chance': 4, 'distance': 15, 'law': 2, 'multicast': 3, 'priority': 11},
    {'spell_name': 'magic_shield_spell', 'label': 'magic_shield', 'msg': 'This magical buckler will offer some modest protection to vulnerable wizards.', 'chance': 6, 'distance': 0, 'law': 1, 'multicast': 1, 'priority': 23},
    {'spell_name': 'magic_armour_spell', 'label': 'magic_armour', 'msg': 'A mighty suit of animated armour coalesces around the wearer.', 'chance': 3, 'distance': 0, 'law': 1, 'multicast': 1, 'priority': 23},
    {'spell_name': 'magic_sword_spell', 'label': 'magic_sword', 'msg': 'This fearsome magical weapon can turn a humble wizard into a lethal melee threat - even for the undead!', 'chance': 3, 'distance': 0, 'law': 1, 'multicast': 1, 'priority': 16},
    {'spell_name': 'magic_knife_spell', 'label': 'magic_knife', 'msg': 'By summoning this magical knife a wizard can defend themself from attackers, included undead!', 'chance': 6, 'distance': 0, 'law': 1, 'multicast': 1, 'priority': 16},
    {'spell_name': 'magic_bow_spell', 'label': 'magic_bow', 'msg': 'With this magical longbow, wizards can become deadly ranged hunters stalking even the undead.', 'chance': 4, 'distance': 0, 'law': 1, 'multicast': 1, 'priority': 17},
    {'spell_name': 'magic_wings_spell', 'label': 'magic_wings', 'msg': 'Every wizard wishes they could fly. Way up to the sky. But they can\'t. Until they can.', 'chance': 4, 'distance': 1, 'law': 0, 'multicast': 1, 'priority': 14},
    {'spell_name': 'chaos_law_spell (Law 1)', 'label': 'Law 1', 'msg': 'The fight for order and justice needs a little nudge.', 'chance': 7, 'distance': 0, 'law': 1, 'multicast': 1, 'priority': 5},
    {'spell_name': 'chaos_law_spell (Law 2)', 'label': 'Law 2', 'msg': 'Something\'s gotta change. There will be law.', 'chance': 5, 'distance': 0, 'law': 2, 'multicast': 1, 'priority': 6},
    {'spell_name': 'chaos_law_spell (Chaos 1)', 'label': 'Chaos 1', 'msg': 'You know the thing about chaos? It\'s fair.', 'chance': 7, 'distance': 0, 'law': -1, 'multicast': 1, 'priority': 6},
    {'spell_name': 'chaos_law_spell (Chaos 2)', 'label': 'Chaos 2', 'msg': 'Chaos isn\'t a pit. It\'s a ladder.', 'chance': 5, 'distance': 0, 'law': -2, 'multicast': 1, 'priority': 18},
    {'spell_name': 'shadow_form_spell', 'label': 'shadow_form', 'msg': 'By slipping into their shadow form, wizards can become much faster and more agile.', 'chance': 6, 'distance': 1, 'law': 0, 'multicast': 1, 'priority': 18},
    {'spell_name': 'subversion_spell', 'label': 'subversion', 'msg': 'When a threating creature is getting too close, it might be time to consider recruiting it.', 'chance': 9, 'distance': 7, 'law': 0, 'multicast': 1, 'priority': 18},
    {'spell_name': 'raise_dead_spell', 'label': 'raise_dead', 'msg': 'Needless to mention, when it comes back, it will be undead. And just as deadly as before.', 'chance': 4, 'distance': 4, 'law': -1, 'multicast': 1, 'multicast': 1, 'priority': 18}]

creature_list = [
    {'name': 'king_cobra', 'label': 'King Cobra', 'mov': 1, 'com': 4, 'rcm': 0, 'rng': 0, 'def': 1, 'mnv': 1, 'res': 6, 'status': []},  
    {'name': 'bat', 'label': 'Bat', 'mov': 5, 'com': 1, 'rcm': 0, 'rng': 0, 'def': 1, 'mnv': 4, 'res': 9, 'status': ['flying']},
    {'name': 'goey_blob', 'label': 'Gooey Blob', 'mov': 0, 'com': 0, 'rcm': 0, 'rng': 0, 'def': 3, 'mnv': 0, 'res': 0, 'status': ['spread', 'engulf', 'noCorpse']},
    {'name': 'dire_wolf', 'label': 'Dire Wolf', 'mov': 3, 'com': 3, 'rcm': 0, 'rng': 0, 'def': 2, 'mnv': 2, 'res': 7, 'status': []},
    {'name': 'spectre', 'label': 'Spectre', 'mov': 1, 'com': 4, 'rcm': 0, 'rng': 0, 'def': 2, 'mnv': 4, 'res': 6, 'status': ['undead', 'trans', 'noCorpse']},
    {'name': 'goblin', 'label': 'Goblin', 'mov': 1, 'com': 2, 'rcm': 0, 'rng': 0, 'def': 4, 'mnv': 4, 'res': 4, 'status': []},
    {'name': 'crocodile', 'label': 'Crocodile', 'mov': 1, 'com': 5, 'rcm': 0, 'rng': 0, 'def': 6, 'mnv': 2, 'res': 2, 'status': []},
    {'name': 'green_dragon', 'label': 'Green Dragon', 'mov': 3, 'com': 5, 'rcm': 4, 'rng': 6, 'def': 8, 'mnv': 4, 'res': 4, 'status': ['flying']},
    {'name': 'magic_fire', 'label': 'Magic Fire', 'mov': 0, 'com': 0, 'rcm': 0, 'rng': 0, 'def': 0, 'mnv': 0, 'res': 0, 'status': ['invuln', 'spread', 'trans', 'noCorpse']},
    {'name': 'faun', 'label': 'Faun', 'mov': 1, 'com': 3, 'rcm': 0, 'rng': 0, 'def': 2, 'mnv': 8, 'res': 7, 'status': []},
    {'name': 'vampire', 'label': 'Vampire', 'mov': 4, 'com': 6, 'rcm': 0, 'rng': 0, 'def': 8, 'mnv': 5, 'res': 6, 'status': ['undead', 'trans', 'flying', 'noCorpse']},
    {'name': 'lion', 'label': 'Lion', 'mov': 4, 'com': 6, 'rcm': 0, 'rng': 0, 'def': 4, 'mnv': 3, 'res': 8, 'status': []},
    {'name': 'gryphon', 'label': 'Gryphon', 'mov': 5, 'com': 3, 'rcm': 0, 'rng': 0, 'def': 5, 'mnv': 6, 'res': 5, 'status': ['mount', 'flying']},
    {'name': 'elf', 'label': 'Elf', 'mov': 1, 'com': 1, 'rcm': 2, 'rng': 6, 'def': 2, 'mnv': 7, 'res': 5, 'status': []},
    {'name': 'horse', 'label': 'Horse', 'mov': 4, 'com': 1, 'rcm': 0, 'rng': 0, 'def': 3, 'mnv': 1, 'res': 8, 'status': ['mount']},
    {'name': 'orc', 'label': 'Orc', 'mov': 1, 'com': 2, 'rcm': 0, 'rng': 0, 'def': 4, 'mnv': 4, 'res': 4, 'status': []},
    {'name': 'red_dragon', 'label': 'Red Dragon', 'mov': 3, 'com': 7, 'rcm': 3, 'rng': 5, 'def': 9, 'mnv': 5, 'res': 4, 'status': ['flying']},
    {'name': 'troll', 'label': 'Troll', 'mov': 1, 'com': 4, 'rcm': 0, 'rng': 0, 'def': 8, 'mnv': 1, 'res': 4, 'status': []},
    {'name': 'unicorn', 'label': 'Unicorn', 'mov': 4, 'com': 5, 'rcm': 0, 'rng': 0, 'def': 4, 'mnv': 7, 'res': 9, 'status': ['mount']},
    {'name': 'pegasus', 'label': 'Pegasus', 'mov': 5, 'com': 2, 'rcm': 0, 'rng': 0, 'def': 4, 'mnv': 7, 'res': 6, 'status': ['mount', 'flying']},
    {'name': 'manticore', 'label': 'Manticore', 'mov': 5, 'com': 3, 'rcm': 1, 'rng': 3, 'def': 6, 'mnv': 8, 'res': 6, 'status': ['mount', 'flying']},
    {'name': 'ghost', 'label': 'Ghost', 'mov': 2, 'com': 1, 'rcm': 0, 'rng': 0, 'def': 3, 'mnv': 6, 'res': 9, 'status': ['undead', 'trans', 'flying', 'noCorpse']},
    {'name': 'wraith', 'label': 'Wraith', 'mov': 2, 'com': 5, 'rcm': 0, 'rng': 0, 'def': 5, 'mnv': 5, 'res': 4, 'status': ['undead', 'noCorpse']},
    {'name': 'bear', 'label': 'Bear', 'mov': 2, 'com': 6, 'rcm': 0, 'rng': 0, 'def': 7, 'mnv': 2, 'res': 6, 'status': []},
    {'name': 'gorilla', 'label': 'Gorilla', 'mov': 1, 'com': 6, 'rcm': 0, 'rng': 0, 'def': 5, 'mnv': 2, 'res': 4, 'status': []},
    {'name': 'skeleton', 'label': 'Skeleton', 'mov': 1, 'com': 3, 'rcm': 0, 'rng': 0, 'def': 2, 'mnv': 4, 'res': 3, 'status': ['undead', 'noCorpse']},
    {'name': 'ogre', 'label': 'Ogre', 'mov': 1, 'com': 4, 'rcm': 0, 'rng': 0, 'def': 7, 'mnv': 6, 'res': 3, 'status': []},
    {'name': 'zombie', 'label': 'Zombie', 'mov': 1, 'com': 1, 'rcm': 0, 'rng': 0, 'def': 1, 'mnv': 3, 'res': 2, 'status': ['undead', 'noCorpse']},
    {'name': 'harpy', 'label': 'Harpy', 'mov': 5, 'com': 4, 'rcm': 0, 'rng': 0, 'def': 2, 'mnv': 5, 'res': 8, 'status': ['flying']},
    {'name': 'eagle', 'label': 'Eagle', 'mov': 6, 'com': 3, 'rcm': 0, 'rng': 0, 'def': 3, 'mnv': 2, 'res': 8, 'status': ['flying']},
    {'name': 'hydra', 'label': 'Hydra', 'mov': 1, 'com': 7, 'rcm': 0, 'rng': 0, 'def': 8, 'mnv': 6, 'res': 4, 'status': []},
    {'name': 'giant_rat', 'label': 'Giant Rat', 'mov': 3, 'com': 1, 'rcm': 0, 'rng': 0, 'def': 1, 'mnv': 2, 'res': 8, 'status': []},
    {'name': 'centaur', 'label': 'Centaur', 'mov': 4, 'com': 1, 'rcm': 2, 'rng': 4, 'def': 3, 'mnv': 5, 'res': 5, 'status': ['mount']},
    {'name': 'giant', 'label': 'Giant', 'mov': 2, 'com': 9, 'rcm': 0, 'rng': 0, 'def': 7, 'mnv': 5, 'res': 6, 'status': []},
    {'name': 'golden_dragon', 'label': 'Golden Dragon', 'mov': 3, 'com': 7, 'rcm': 5, 'rng': 4, 'def': 9, 'mnv': 5, 'res': 4, 'status': ['flying']},
    {'name': 'dark_citadel', 'label': 'Dark Citadel', 'mov': 0, 'com': 0, 'rcm': 0, 'rng': 0, 'def': 0, 'mnv': 0, 'res': 0, 'status': ['mount', 'invuln', 'expires', 'struct', 'noCorpse']},
    {'name': 'magic_castle', 'label': 'Magic Castle', 'mov': 0, 'com': 0, 'rcm': 0, 'rng': 0, 'def': 0, 'mnv': 0, 'res': 0, 'status': ['mount', 'invuln', 'expires', 'struct', 'noCorpse']},
    {'name': 'shadow_wood', 'label': 'Shadow Wood', 'mov': 0, 'com': 2, 'rcm': 0, 'rng': 0, 'def': 4, 'mnv': 0, 'res': 9, 'status': ['tree', 'noCorpse']},
    {'name': 'magic_wood', 'label': 'Magic Wood', 'mov': 0, 'com': 0, 'rcm': 0, 'rng': 0, 'def': 5, 'mnv': 0, 'res': 9, 'status': ['mountAny', 'tree', 'expires', 'expiresGivesSpell', 'noCorpse']},
    {'name': 'wall', 'label': 'Wall', 'mov': 0, 'com': 0, 'rcm': 0, 'rng': 0, 'def': 0, 'mnv': 0, 'res': 0, 'status': ['invuln', 'struct', 'noCorpse']}]

animation_list = [{'name': 'king_cobra',
  'shortname': 'COBRA',
  'frames': [('kingcobrasprite0', GREEN),
              ('kingcobrasprite1', GREEN),
              ('kingcobrasprite2', GREEN),
              ('kingcobrasprite1', GREEN),
              ('deadcobrasprite', GREEN)]},
 {'name': 'bat',
  'shortname': 'BAT',
  'frames': [('batsprite0', BRIGHT_WHITE),
              ('batsprite2', BRIGHT_WHITE),
              ('batsprite1', BRIGHT_WHITE),
              ('batsprite2', BRIGHT_WHITE),
              ('deadbatsprite', BRIGHT_WHITE)]},
 {'name': 'goey_blob',
  'shortname': 'BLOB',
  'frames': [('blobsprite0', GREEN),
              ('blobsprite1', GREEN),
              ('blobsprite2', GREEN),
              ('blobsprite1', GREEN),
              ('deadblobsprite', BRIGHT_GREEN)]},
 {'name': 'dire_wolf',
  'shortname': 'WOLF',
  'frames': [('wolfsprite0', BRIGHT_YELLOW),
              ('wolfsprite1', BRIGHT_YELLOW),
              ('wolfsprite2', BRIGHT_YELLOW),
              ('wolfsprite1', BRIGHT_YELLOW),
              ('deadwolfsprite', BRIGHT_YELLOW)]},
 {'name': 'spectre',
  'shortname': 'SPECTRE',
  'frames': [('spectrsprite', BRIGHT_WHITE),
              ('spectrsprite', BRIGHT_CYAN),
              ('spectrsprite', MAGENTA),
              ('spectrsprite', BLUE),
              ('deadspectresprite', CYAN)]},
 {'name': 'goblin',
  'shortname': 'GOBLIN',
  'frames': [('goblinsprite0', MAGENTA),
              ('goblinsprite1', MAGENTA),
              ('goblinsprite2', MAGENTA),
              ('goblinsprite1', MAGENTA),
              ('deadgoblinsprite', MAGENTA)]},
 {'name': 'crocodile',
  'shortname': 'CROCODILE',
  'frames': [('crocodilesprite0', GREEN),
              ('crocodilesprite1', GREEN),
              ('crocodilesprite2', GREEN),
              ('crocodilesprite1', GREEN),
              ('deadcrocodilesprite', GREEN)]},
 {'name': 'green_dragon',
  'shortname': 'GREEN D',
  'frames': [('greendragonsprite0', GREEN),
              ('greendragonsprite1', GREEN),
              ('greendragonsprite2', GREEN),
              ('greendragonsprite1', GREEN),
              ('deaddragonsprite', GREEN)]},
 {'name': 'vampire',
  'shortname': 'VAMPIRE',
  'frames': [('vampiresprite0', RED),
              ('vampiresprite1', RED),
              ('vampiresprite2', RED),
              ('vampiresprite1', RED),
              ('deadvampiresprite', RED)]},
 {'name': 'faun',
  'shortname': 'FAUN',
  'frames': [('faunsprite0', BRIGHT_WHITE),
              ('faunsprite1', BRIGHT_WHITE),
              ('faunsprite2', BRIGHT_WHITE),
              ('faunsprite1', BRIGHT_WHITE),
              ('deadfaunsprite', BRIGHT_WHITE)]},
 {'name': 'lion',
  'shortname': 'LION',
  'frames': [('lionsprite0', BRIGHT_YELLOW),
              ('lionsprite1', BRIGHT_YELLOW),
              ('lionsprite2', BRIGHT_YELLOW),
              ('lionsprite1', BRIGHT_YELLOW),
              ('deadlionsprite', BRIGHT_YELLOW)]},
 {'name': 'gryphon',
  'shortname': 'GRYPHON',
  'frames': [('gryphonsprite0', WHITE),
              ('gryphonsprite1', WHITE),
              ('gryphonsprite2', WHITE),
              ('gryphonsprite1', WHITE),
              ('deadgryphonsprite', WHITE)]},
 {'name': 'elf',
  'shortname': 'ELF',
  'frames': [('elfsprite0', GREEN),
              ('elfsprite1', GREEN),
              ('elfsprite2', GREEN),
              ('elfsprite3', GREEN),
              ('deadelfsprite', GREEN)]},
 {'name': 'horse',
  'shortname': 'HORSE',
  'frames': [('horsesprite0', YELLOW),
              ('horsesprite1', YELLOW),
              ('horsesprite2', YELLOW),
              ('horsesprite1', YELLOW),
              ('deadhorsesprite', YELLOW)]},
 {'name': 'orc',
  'shortname': 'ORC',
  'frames': [('orcsprite0', BRIGHT_CYAN),
              ('orcsprite1', BRIGHT_CYAN),
              ('orcsprite2', BRIGHT_CYAN),
              ('orcsprite1', BRIGHT_CYAN),
              ('deadorcsprite', BRIGHT_CYAN)]},
 {'name': 'red_dragon',
  'shortname': 'RED D',
  'frames': [('reddragonsprite0', RED),
              ('reddragonsprite1', RED),
              ('reddragonsprite2', RED),
              ('reddragonsprite1', RED),
              ('deaddragonsprite', RED)]},
 {'name': 'magic_fire',
  'shortname': 'FIRE',
  'frames': [('firesprite0', BRIGHT_YELLOW),
              ('firesprite3', BRIGHT_YELLOW),
              ('firesprite2', BRIGHT_YELLOW),
              ('firesprite1', BRIGHT_YELLOW)]},
 {'name': 'manticore',
  'shortname': 'MANTICORE',
  'frames': [('manticoresprite0', BRIGHT_YELLOW),
              ('manticoresprite1', BRIGHT_YELLOW),
              ('manticoresprite2', BRIGHT_YELLOW),
              ('manticoresprite1', BRIGHT_YELLOW),
              ('deadmanticoresprite', BRIGHT_YELLOW),
              ('deadmanticoresprite', YELLOW)]},
 {'name': 'troll',
  'shortname': 'TROLL',
  'frames': [('trollsprite0', BRIGHT_GREEN),
              ('trollsprite1', BRIGHT_GREEN),
              ('trollsprite2', BRIGHT_GREEN),
              ('trollsprite1', BRIGHT_GREEN),
              ('deadtrollsprite', BRIGHT_GREEN)]},
 {'name': 'unicorn',
  'shortname': 'UNICORN',
  'frames': [('unicornsprite0', BRIGHT_CYAN),
              ('unicornsprite1', BRIGHT_CYAN),
              ('unicornsprite2', BRIGHT_CYAN),
              ('unicornsprite1', BRIGHT_CYAN),
              ('deadunicornsprite', BRIGHT_CYAN)]},
 {'name': 'ghost',
  'shortname': 'GHOST',
  'frames': [('ghostsprite0', CYAN),
              ('ghostsprite1', BRIGHT_CYAN),
              ('ghostsprite2', CYAN),
              ('ghostsprite3', BRIGHT_CYAN)]},
 {'name': 'wraith',
  'shortname': 'WRAITH',
  'frames': [('wraithsprite0', BRIGHT_CYAN),
              ('wraithsprite1', BRIGHT_CYAN),
              ('wraithsprite3', BRIGHT_CYAN),
              ('wraithsprite2', BRIGHT_CYAN)]},
 {'name': 'bear',
  'shortname': 'BEAR',
  'frames': [('bearsprite0', RED),
              ('bearsprite1', RED),
              ('bearsprite2', RED),
              ('bearsprite2', RED),
              ('deadbearsprite', RED)]},
 {'name': 'gorilla',
  'shortname': 'GORILLA',
  'frames': [('gorillasprite0', YELLOW),
              ('gorillasprite1', YELLOW),
              ('gorillasprite2', YELLOW),
              ('gorillasprite1', YELLOW),
              ('deadgorillasprite', YELLOW)]},
 {'name': 'skeleton',
  'shortname': 'SKELETON',
  'frames': [('skeletonsprite0', BRIGHT_WHITE),
              ('skeletonsprite1', BRIGHT_WHITE),
              ('skeletonsprite2', BRIGHT_WHITE),
              ('skeletonsprite1', BRIGHT_WHITE)]},
 {'name': 'ogre',
  'shortname': 'OGRE',
  'frames': [('ogresprite0', RED),
              ('ogresprite1', RED),
              ('ogresprite2', RED),
              ('ogresprite1', RED),
              ('deadogresprite', RED)]},
 {'name': 'zombie',
  'shortname': 'ZOMBIE',
  'frames': [('zombiesprite0', BRIGHT_CYAN),
              ('zombiesprite1', BRIGHT_CYAN),
              ('zombiesprite2', BRIGHT_CYAN),
              ('zombiesprite3', BRIGHT_CYAN)]},
 {'name': 'harpy',
  'shortname': 'HARPY',
  'frames': [('harpysprite0', BRIGHT_CYAN),
              ('harpysprite1', BRIGHT_CYAN),
              ('harpysprite2', BRIGHT_CYAN),
              ('harpysprite1', BRIGHT_CYAN),
              ('deadharpysprite', BRIGHT_CYAN)]},
 {'name': 'pegasus',
  'shortname': 'PEGASUS',
  'frames': [('pegasussprite0', BRIGHT_WHITE),
              ('pegasussprite1', BRIGHT_WHITE),
              ('pegasussprite2', BRIGHT_WHITE),
              ('pegasussprite1', BRIGHT_WHITE),
              ('deadpegasussprite', BRIGHT_WHITE)]},
 {'name': 'eagle',
  'shortname': 'EAGLE',
  'frames': [('eaglesprite0', BRIGHT_YELLOW),
              ('eaglesprite1', BRIGHT_YELLOW),
              ('eaglesprite2', BRIGHT_YELLOW),
              ('eaglesprite1', BRIGHT_YELLOW),
              ('deadeaglesprite', BRIGHT_YELLOW)]},
 {'name': 'hydra',
  'shortname': 'HYDRA',
  'frames': [('hydrasprite0', GREEN),
              ('hydrasprite1', GREEN),
              ('hydrasprite2', GREEN),
              ('hydrasprite1', GREEN),
              ('deadhydrasprite', GREEN)]},
 {'name': 'giant_rat',
  'shortname': 'RAT',
  'frames': [('giantratsprite0', WHITE),
              ('giantratsprite1', WHITE),
              ('giantratsprite2', WHITE),
              ('giantratsprite1', WHITE),
              ('deadgiantratsprite', WHITE)]},
 {'name': 'centaur',
  'shortname': 'CENTAUR',
  'frames': [('centaursprite0', YELLOW),
              ('centaursprite1', YELLOW),
              ('centaursprite2', YELLOW),
              ('centaursprite1', YELLOW),
              ('deadcentaursprite', YELLOW)]},
 {'name': 'giant',
  'shortname': 'GIANT',
  'frames': [('giantsprite0', CYAN),
              ('giantsprite1', CYAN),
              ('giantsprite2', CYAN),
              ('giantsprite1', CYAN),
              ('deadgiantsprite', CYAN)]},
 {'name': 'golden_dragon',
  'shortname': 'GOLD',
  'frames': [('goldendragonsprite0', BRIGHT_YELLOW),
              ('goldendragonsprite1', BRIGHT_YELLOW),
              ('goldendragonsprite2', BRIGHT_YELLOW),
              ('goldendragonsprite1', BRIGHT_YELLOW),
              ('deadgoldendragonsprite', BRIGHT_YELLOW)]},
 {'name': 'dark_citadel',
  'shortname': 'CITADEL',
  'frames': [('darkcitadelsprite', MAGENTA),
              ('darkcitadelsprite', MAGENTA),
              ('darkcitadelsprite', BRIGHT_MAGENTA),
              ('darkcitadelsprite', BRIGHT_MAGENTA),
              ('darkcitadelsprite', BRIGHT_MAGENTA)]},
 {'name': 'magic_castle',
  'shortname': 'CASTLE',
  'frames': [('magiccastlesprite', BRIGHT_CYAN),
              ('magiccastlesprite', CYAN),
              ('magiccastlesprite', BRIGHT_CYAN),
              ('magiccastlesprite', CYAN)]},
 {'name': 'shadow_wood',
  'shortname': 'S.WOOD',
  'frames': [('shadowwoodsprite', CYAN),
              ('shadowwoodsprite', CYAN),
              ('shadowwoodsprite', BRIGHT_CYAN),
              ('shadowwoodsprite', BRIGHT_CYAN)]},
 {'name': 'magic_wood',
  'shortname': 'M.WOOD',
  'frames': [('magicwoodsprite', BRIGHT_GREEN),
              ('magicwoodsprite', GREEN),
              ('magicwoodsprite', YELLOW),
              ('magicwoodsprite', BRIGHT_YELLOW)]},
 {'name': 'wall',
  'shortname': 'WALL',
  'frames': [('wallsprite', YELLOW),
              ('wallsprite', RED),
              ('wallsprite', YELLOW),
              ('wallsprite', RED)]}]

starting_position_data = [
    [65, 77],
    [23, 129, 141],
    [17, 29, 129, 141],
    [7, 48, 62, 147, 155],
    [7, 16, 30, 128, 151, 142],
    [7, 17, 29, 96, 110, 148, 154],
    [0, 7, 14, 64, 78, 144, 151, 158]]
